---
title: "a3_task3_sachi_shiroma"
author: "Sachi Shiroma"
date: "10/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, options(digits = 2))
library(here)
library(tidyverse)
library(janitor)
library(kableExtra)
library(lubridate)
```

# Read in the Data
```{r}
urchins <- read_csv(here("data", "urchins.csv"))
```

# Clean the Names 
```{r}
urchins_clean <- urchins %>% 
clean_names()
```


# Data Visualization 
```{r}
ggplot(data = urchins_clean, aes(x = size, fill = common_name)) + #assingning graph values
  geom_histogram(bins = 10) + #reducing bin size to 10
  scale_fill_manual(values = c("purple", "red"), name = "Urchin Type") + #assigning names for the key
  labs(x = "Size", y = "Urchins", title = "Sea Urchins by Color and Size" )+ #creating titles
facet_wrap(~ common_name) #splitting the graph into two by different urchins

```

F.1 This data shows the different sizes of two different types of sea urchins (red and purple).

```{r}
urchin_stats <- urchins_clean %>% 
group_by(common_name) %>% 
summarize(
  "Sea Urchin Mean" = mean(size),
  "Median" = median(size),
  "SD of Urchins" = sd(size),
   "Sample Size"= n()) %>% 
rename("Sea Urchins" = common_name)
```

```{r}
purple_urchins <- urchins_clean %>% 
  group_by(common_name = "Purple Urchin") %>% 
  mutate(dates_new = mdy(date)) %>% 
  mutate(years = year(dates_new)) %>% 
  mutate(site_full = case_when(
    site == "NAPL" ~ "Naples Reef",
    site == "AQUE" ~ "Arroyo Quemado Reef",
    site == "CARP" ~ "Carpinteria Reef",
    site == "MOHK" ~ "Mohawk Reef",
    site == "IVEE" ~ "Isla Vista Reef"))

```

```{r}
purple_urchins_site_year <- purple_urchins %>% 
  group_by(site_full, years) %>% 
  summarize(count = n()) 
  
```

```{r}
ggplot(data = purple_urchins_site_year, aes(x = years, y = count, color = site_full)) + #assingning graph values
  geom_line() + 
  labs(x = "site", y = "year", title = "Numer of Sea Urchins by Year and Site") + 
  theme(axis.text.x = element_text(angle = 65, hjust = 1)) +
  scale_x_continuous(breaks = c(2008, 2010, 2012, 2014, 2016, 2018, 2020))+
  facet_wrap(~ site_full, scales = 'free')
```

