---
title: "Curriculum Vitae"  
---

# Education
Masters in Environmental Science & Management, (Expected 06/2023)
Pollution Prevention and Remediation
Bren School of Environmental Science & Management – University of California, Santa Barbara (UCSB)

Bachelor of Arts in Sociology – Race and Ethnic Studies,  (12/2020) 
San Jose State University (SJSU)

# Research
Researcher – City of San Jose, Downtown San Jose, CA (05/2019)
Recorded quantitative and qualitative data regarding pedestrians littering habits
Presented and organized data using SPSS for 3 project leaders
Helped create solutions on how to reduce trash in the streets of San Jose

Lead Prototype Designer– Braven, San Jose, CA (05/2019)
Collaborated with 8 other students to present and create a social movement prototype (#ishareyoushare) for Sutter Health

# Experience 
Senior year of my quantitative and qualitative Sociology course, we were selected to help the City of San Jose by collecting and analyzing data regarding littering habits in downtown San Jose.  I also used to volunteer regularly in various local environmental clubs such as Keep Coyote Creek Beautiful (KCCB) by participating in weekly trash clean ups.

<a href = "Sachi_Resume.pdf" target = '_blank'>Click here for my full resume.</a>






